name: Mervin Fevrier
favicon: null
layout_spectrum: 0.8529170933179557
typography_spectrum: 0.3722168020904064
title: Resume
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5880504280794412
  lightness: 0.4174087659921497
  saturation: 0.3904540631920099
  rhythmicContrast: 0.6611237439792603
purpose: []
